04_pjt/영화/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
]

04_pjt/영화/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=10, blank=True)
    last_name = models.CharField(max_length=10, blank=True)

04_pjt/영화/accounts/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='이메일 주소')
    first_name = forms.CharField(label='성', max_length=10, required=True)
    last_name = forms.CharField(label='이름', max_length=10, required=True)
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(label='이메일 주소')
    first_name = forms.CharField(label='성', max_length=10, required=True)
    last_name = forms.CharField(label='이름', max_length=10, required=True)
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

04_pjt/영화/accounts/views.py
from django.shortcuts import render, redirect

# 로그인
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login

# 로그아웃
from django.contrib.auth import logout as auth_logout

# 회원가입
from .forms import CustomUserCreationForm, CustomUserChangeForm

# 비밀번호변경
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('movies:index')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def change_password(request, user_pk):
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


def delete(request):
    request.user.delete()
    return redirect('movies:index')

04_pjt/영화/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>PASSWORD CHANGE</h1>
<hr>
<form action="{% url "change_password" user.pk%}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">비밀번호 변경</button>
</form>
{% endblock content %}

04_pjt/영화/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>LOGIN PAGE</h1>
<hr>
<form action="{% url "accounts:login" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">로그인</button>
</form>
{% endblock content %}

04_pjt/영화/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>SIGNUP PAGE</h1>
<hr>
<form action="{% url "accounts:signup" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">회원가입</button>

</form>
{% endblock content %}

04_pjt/영화/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
<style>
    .change-container > *{
        margin-bottom: 8px;
    }
</style>
<h1>UPDATE PAGE</h1>
<hr>
<form action="{% url "accounts:update" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">회원정보 수정</button>
</form>
<hr>
<div class="change-container">
    <button class="btn btn-secondary" href="{% url "change_password" user.pk %}">비밀번호변경</button>
    <form action="{% url "accounts:delete" %}">
        {% csrf_token %}
        <button class="btn btn-danger" href="{% url "accounts:delete" %}" onclick="return confirm('정말로 회원을 탈퇴하시겠습니까?')">회원탈퇴</button>
    </form>
</div>
{% endblock content %}