04_pjt/영화/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

04_pjt/영화/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    # def __str__(self):
    #     return self.title

04_pjt/영화/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

04_pjt/영화/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:index')
    else:
        form = MovieForm()
    context = {
        'form':form,
    }
    return render(request, 'movies/create.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)


def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

04_pjt/영화/movies/templates/movies/create.html
{% extends "base.html" %}

{% block content %}
<h1>Create</h1>
<form action="{% url "movies:create" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="제출">
</form>
{% endblock content %}

04_pjt/영화/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
<style>
    .update-delete {
        display: flex;
        gap: 5px;
    }
</style>


<h1>DETAIL PAGE</h1>
<h3>{{ movie.title }}</h3>
<p>{{ movie.description }}</p>

<hr>
<div class='update-delete'>
    <a class="btn btn-secondary" href="{% url "movies:update" movie.pk%}" role="button">UPDATE</a>
    <form action="{% url "movies:delete" movie.pk %}" method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" onclick="return confirm('정말로 삭제하시겠습니까?')">DELETE</button>
    </form>
</div>

<hr>
<a class="btn btn-primary" href="{% url "movies:index" %}" role="button">BACK</a>
{% endblock content %}

04_pjt/영화/movies/templates/movies/index.html
{% extends "base.html" %}

{% block content %}
<style>
    .flex-container {
        display: flex;
        flex-wrap: wrap; /* 요소가 넘칠 경우 자동으로 다음 줄로 이동 */
    }
    
    .flex-item {
        flex: 0 0 calc(50% - 20px); /* 각 아이템의 너비를 50%로 설정하고 간격을 고려 */
        margin: 10px; /* 아이템 간격 설정 */
    }
</style>


<h1>INDEX PAGE</h1>
<hr>
<div class='flex-container'>
    {% for movie in movies %}
    <div class='flex-item'>
        <div class="card">
            <h5 class="card-header">{{movie.title}}</h5>
            <div class="card-body">
                <p class="card-text">{{movie.description}}</p>
                <a href="{% url "movies:detail" movie.pk %}" class="btn btn-primary">DETAIL</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

04_pjt/영화/movies/templates/movies/update.html
{% extends "base.html" %}

{% block content %}
<form action="{% url "movies:update" movie.pk%}" method='POST'>
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit">
</form>
{% endblock content %}